title: "my gloomy corner"
description: "the bestest darkest website on the web"

github: "https://vitimesthree.github.io"
baseurl: "/my-gloomy-corner"
imageurl: "/my-gloomy-corner/assets/images/"
audiourl: "/my-gloomy-corner/assets/audio/"
videourl: "/my-gloomy-corner/assets/videos/"


defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: "banner.png"
  - scope:
      path: "games/"
    values:
      layout: "empty"

kramdown:
  auto_ids: "false"


gems:
- jekyll-auto-image